source "https://rubygems.org"

gem "rails", "~> 7.2"
gem "pg", "~> 1.5"
gem "rack-cors"
gem "puma", "~> 6.4"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", ">= 1.4.4"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", "~> 6.0"
end
